class CONFIG:
    PATH_URLS_START = "./urls/urls_start.txt"
    PATH_URLS_END = "./urls/urls_end.txt"
    PATH_URLS_lnk_END = "./urls/urls_lnk_end.txt"
    PATH_URLS_END_CUSTOM = "./urls/urls_end_custom.txt"
    PATH_FILE_LOG = "./logs/logs_error.log"
    URL_PAGE_OFFICE = "https://is.gd/create.php"
    URL_PAGE_CHECKURL = "https://is.gd/checkurl.php"
    CUSTOM_URL = "VIEW_PHOTO"
    USER_EMAIL = "email"
    USER_PASS = "pass"
    URL_lnk_shorturl = "https://lnk.bio/manage/shorturl"
    URL_lnk_login = "https://lnk.bio/es/login/credentials"
    TITLE_lnk_URL = "URL lnk"
    SHOW_GRAPHICAL_INTERFACE = True
